# Generated by Django 4.1.4 on 2023-05-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll', models.IntegerField(unique=True, verbose_name='Roll_No')),
                ('city', models.CharField(max_length=255)),
            ],
        ),
    ]
